# Generated by Django 2.2.5 on 2020-04-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condicion_consumo',
            fields=[
                ('nombre_condicion', models.CharField(max_length=30, unique=True)),
                ('tipo_condicion', models.CharField(max_length=2, primary_key=True, serialize=False)),
            ],
        ),
    ]
