# Generated by Django 2.2.5 on 2020-04-23 15:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteTipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_mov', models.CharField(max_length=2)),
                ('descripcion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id_bodega', models.CharField(default='DUTR', max_length=4, primary_key=True, serialize=False)),
                ('siglas', models.CharField(max_length=2)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('F', 'Facturable'), ('N', 'No facturable'), ('T', 'Transito')], default='F', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='CentroCosto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('cuenta_contab', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='DevolucionCondicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=45)),
                ('valor', models.FloatField()),
            ],
            options={
                'unique_together': {('descripcion',)},
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_desc', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExoRubro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('unidades', models.BooleanField(default=False)),
                ('costo', models.BooleanField(default=False)),
                ('precio', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ExoTipo',
            fields=[
                ('id_exo', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='MarcaItem',
            fields=[
                ('siglas', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='MarcaVehiculo',
            fields=[
                ('siglas', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModeloVehiculo',
            fields=[
                ('id_modelo', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=45)),
                ('cilindraje', models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.5)])),
                ('combustible', models.CharField(choices=[('G', 'Gasolina'), ('D', 'Diesel')], default='G', max_length=1)),
                ('anyo', models.CharField(max_length=10)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.MarcaVehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='N1Rubro',
            fields=[
                ('id_n1', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('codigo_sac', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='N2Familia',
            fields=[
                ('id_n2', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=3)),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.N1Rubro')),
            ],
        ),
        migrations.CreateModel(
            name='N3Producto',
            fields=[
                ('id_n3', models.CharField(max_length=251, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('codfabrica', models.CharField(max_length=20)),
                ('sac', models.CharField(max_length=20)),
                ('minimo', models.PositiveIntegerField(default=0)),
                ('maximo', models.PositiveIntegerField(default=0)),
                ('descontinuado', models.CharField(choices=[('S', 'Producto Descontinuado'), ('N', 'Producto Activo')], default='N', max_length=1)),
                ('costo', models.CharField(choices=[('S', 'Puede ser sin costo'), ('N', 'Debe tener costo')], default='N', max_length=1)),
                ('entero', models.CharField(choices=[('S', 'Se vende por partes de la medida'), ('N', 'Se vende por toda la medida')], default='N', max_length=1)),
                ('naturaleza', models.CharField(choices=[('C', 'Combo'), ('U', 'Unico'), ('P', 'Procesado'), ('E', 'Elemento'), ('S', 'Servicio')], default='U', max_length=1)),
                ('aplicacion', models.ManyToManyField(default='NE.NEE99', to='inv.ModeloVehiculo')),
                ('exorubro', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='inv.ExoRubro')),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.N2Familia')),
            ],
        ),
        migrations.CreateModel(
            name='N4Item',
            fields=[
                ('id_n4', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('preciomax', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('preciomin', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('codanterior', models.CharField(max_length=9)),
                ('codbarra', models.CharField(max_length=20, unique=True)),
                ('sac', models.CharField(max_length=20)),
                ('cantidad_impuesto', models.PositiveIntegerField(default=15)),
                ('minimo', models.PositiveIntegerField(default=0)),
                ('maximo', models.PositiveIntegerField(default=0)),
                ('descontinuado', models.CharField(choices=[('S', 'Item Descontinuado'), ('N', 'Item Activo')], default='N', max_length=1)),
                ('exotipo', models.ForeignKey(default='G', on_delete=django.db.models.deletion.CASCADE, to='inv.ExoTipo')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.MarcaItem')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.N3Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id_precio', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('siglas', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=255)),
                ('telefonos', models.CharField(max_length=255)),
                ('encabezado', models.CharField(max_length=255)),
                ('pie_pagina', models.CharField(max_length=255)),
                ('serie', models.CharField(default='A', max_length=1, unique=True)),
                ('usuarios', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Um',
            fields=[
                ('id_um', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='item_costo',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inv.N4Item')),
                ('existencia', models.PositiveIntegerField(default=0)),
                ('costo', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('saldo', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('preciomax', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('preciomin', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
        ),
        migrations.CreateModel(
            name='TrasladoMsr',
            fields=[
                ('referencia', models.CharField(default='TR-DU-31129999-01-DU', max_length=20, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nota', models.CharField(max_length=255)),
                ('estado', models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='inv.Estado')),
                ('sucursal', models.ForeignKey(default='DU', on_delete=django.db.models.deletion.CASCADE, to='inv.Sucursal')),
                ('sucursalD', models.ForeignKey(default='DU', on_delete=django.db.models.deletion.CASCADE, related_name='Destino', to='inv.Sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='TrasladoDettemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('costo', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('bodegaD', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Destinotemp', to='inv.Bodega')),
                ('bodegaO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Origentemp', to='inv.Bodega')),
                ('estado', models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='inv.Estado')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.N4Item')),
                ('referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.TrasladoMsr')),
            ],
        ),
        migrations.CreateModel(
            name='TrasladoDet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('costo', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('recepcionado', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('bodegaD', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Destino', to='inv.Bodega')),
                ('bodegaO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Origen', to='inv.Bodega')),
                ('estado', models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='inv.Estado')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.N4Item')),
                ('referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.TrasladoMsr')),
            ],
        ),
        migrations.CreateModel(
            name='TempCatalogoMsr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrador', models.IntegerField(default=1)),
                ('cedula', models.CharField(default='0', max_length=15)),
                ('nombre', models.CharField(default='PARTICULAR / INDIVIDUAL', max_length=100)),
                ('cooperativa', models.IntegerField(default=1)),
                ('membresia', models.IntegerField(default=1)),
                ('tipopago', models.IntegerField(default=2)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.Sucursal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TempCatalogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.N4Item')),
                ('bodega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inv.Bodega')),
                ('maestro', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inv.TempCatalogoMsr')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.Sucursal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='N4ItemProduccion',
            fields=[
                ('referencia', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('nota', models.CharField(max_length=50)),
                ('fecha_venc', models.CharField(max_length=10)),
                ('bodegad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DestinoProduccion', to='inv.Bodega')),
                ('bodegao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OrigenProduccion', to='inv.Bodega')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.N4Item')),
            ],
        ),
        migrations.CreateModel(
            name='N4ItemImagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.ImageField(upload_to='inv/Item/')),
                ('nota', models.CharField(max_length=255)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.N4Item')),
            ],
        ),
        migrations.CreateModel(
            name='N4ItemCombo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion', models.PositiveIntegerField()),
                ('cantidad', models.PositiveIntegerField()),
                ('precio', models.FloatField()),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Combo', to='inv.N4Item')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product', to='inv.N4Item')),
            ],
        ),
        migrations.CreateModel(
            name='N3ProductoImagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.ImageField(upload_to='inv/Producto/')),
                ('nota', models.CharField(max_length=255)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inv.N3Producto')),
            ],
        ),
        migrations.AddField(
            model_name='n3producto',
            name='medida',
            field=models.ForeignKey(default='UNI', on_delete=django.db.models.deletion.CASCADE, to='inv.Um'),
        ),
        migrations.AddField(
            model_name='modelovehiculo',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.TipoVehiculo'),
        ),
        migrations.CreateModel(
            name='ExistenciaBodega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.Bodega')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.N4Item')),
            ],
        ),
        migrations.CreateModel(
            name='DevolucionMsr',
            fields=[
                ('referencia', models.CharField(default='DE-DU-31129999-00001', max_length=20, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nota', models.CharField(max_length=255)),
                ('notacredito', models.CharField(max_length=255)),
                ('rem', models.CharField(blank=True, default='REM-001', max_length=20, null=True)),
                ('factura', models.CharField(blank=True, default='SF-001', max_length=20, null=True)),
                ('costo_total', models.FloatField(blank=True, null=True)),
                ('precio_total', models.FloatField(blank=True, null=True)),
                ('impuesto_total', models.FloatField(blank=True, null=True)),
                ('penalizacion_total', models.FloatField(blank=True, null=True)),
                ('monto_total', models.FloatField(blank=True, null=True)),
                ('estado', models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='inv.Estado')),
                ('sucursal', models.ForeignKey(default='DU', on_delete=django.db.models.deletion.CASCADE, to='inv.Sucursal')),
            ],
        ),
        migrations.AddField(
            model_name='bodega',
            name='sucursal',
            field=models.ForeignKey(blank=True, default='DU', null=True, on_delete=django.db.models.deletion.CASCADE, to='inv.Sucursal'),
        ),
        migrations.CreateModel(
            name='AjusteMsr',
            fields=[
                ('referencia', models.CharField(default='AJ-DU-31129999-01-DU', max_length=20, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nota', models.CharField(max_length=255)),
                ('costo_total', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('ajuste', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inv.AjusteTipo')),
                ('centro_costo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inv.CentroCosto')),
                ('estado', models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='inv.Estado')),
                ('sucursal', models.ForeignKey(default='DU', on_delete=django.db.models.deletion.CASCADE, to='inv.Sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='N4ItemXPrecio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.N4Item')),
                ('precio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.Precio')),
            ],
            options={
                'unique_together': {('item', 'precio')},
            },
        ),
        migrations.CreateModel(
            name='N4ItemVencimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=20)),
                ('fecha_venc', models.DateTimeField()),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('fecha_cero', models.CharField(blank=True, default='.', max_length=10, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.N4Item')),
            ],
            options={
                'unique_together': {('item', 'fecha_venc', 'referencia')},
            },
        ),
        migrations.CreateModel(
            name='N4ItemReceta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('costo', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ingrediente', to='inv.N4Item')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Receta', to='inv.N4Item')),
            ],
            options={
                'unique_together': {('receta', 'item')},
            },
        ),
        migrations.CreateModel(
            name='Kardex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('referencia', models.CharField(default='referencia de apertura', max_length=20)),
                ('entrada', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('salida', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('debe', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('haber', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('saldo', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('saldosuc', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('saldobod', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('costounitario', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('existencia', models.PositiveIntegerField(default=0)),
                ('existenciasuc', models.PositiveIntegerField(default=0)),
                ('existenciabod', models.PositiveIntegerField(default=0)),
                ('tipotransaccion', models.CharField(choices=[('EE', 'Entrada'), ('SS', 'Salida'), ('EA', 'Entrada por Ajuste'), ('SA', 'Salida por Ajuste'), ('EC', 'Entrada por Costo'), ('SC', 'Salida por Costo')], default='EE', max_length=2)),
                ('fecha_venc', models.DateField(default='3030-12-31')),
                ('bodega', models.ForeignKey(default='ESTR', on_delete=django.db.models.deletion.CASCADE, to='inv.Bodega')),
                ('estado', models.ForeignKey(default='5', on_delete=django.db.models.deletion.CASCADE, to='inv.Estado')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.N4Item')),
                ('sucursal', models.ForeignKey(default='DU', on_delete=django.db.models.deletion.CASCADE, to='inv.Sucursal')),
            ],
            options={
                'unique_together': {('id', 'sucursal', 'item', 'referencia')},
            },
        ),
        migrations.CreateModel(
            name='item_costo_historico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('existencia', models.PositiveIntegerField(default=0)),
                ('costo', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('saldo', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('preciomax', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('preciomin', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.N4Item')),
            ],
            options={
                'unique_together': {('item', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='DevolucionDettemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venc', models.CharField(blank=True, max_length=10, null=True)),
                ('cantidad', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('costo', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('precio', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('impuesto', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('penalizacion', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('monto', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.Bodega')),
                ('estado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inv.DevolucionCondicion')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.N4Item')),
                ('referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.DevolucionMsr')),
            ],
            options={
                'unique_together': {('referencia', 'bodega', 'item', 'estado')},
            },
        ),
        migrations.CreateModel(
            name='DevolucionDet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venc', models.CharField(blank=True, max_length=10, null=True)),
                ('cantidad', models.FloatField()),
                ('costo', models.FloatField(default=1)),
                ('precio', models.FloatField(default=1)),
                ('impuesto', models.FloatField(default=1)),
                ('penalizacion', models.FloatField(default=1)),
                ('monto', models.FloatField(default=1)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.Bodega')),
                ('estado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inv.DevolucionCondicion')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.N4Item')),
                ('referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.DevolucionMsr')),
            ],
            options={
                'unique_together': {('referencia', 'bodega', 'item', 'estado')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='bodega',
            unique_together={('sucursal', 'siglas')},
        ),
        migrations.CreateModel(
            name='AjusteDettemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venc', models.CharField(blank=True, max_length=10, null=True)),
                ('cantidad', models.FloatField()),
                ('costo', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.Bodega')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.N4Item')),
                ('referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.AjusteMsr')),
            ],
            options={
                'unique_together': {('referencia', 'bodega', 'item')},
            },
        ),
        migrations.CreateModel(
            name='AjusteDet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venc', models.CharField(blank=True, max_length=10, null=True)),
                ('cantidad', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('costo', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.Bodega')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.N4Item')),
                ('referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.AjusteMsr')),
            ],
            options={
                'unique_together': {('referencia', 'bodega', 'item')},
            },
        ),
    ]
