# Generated by Django 2.2.5 on 2020-04-24 10:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodega',
            name='existencia',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bodega',
            name='saldo',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='existencia',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='saldo',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.CreateModel(
            name='sucursal_historico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('existencia', models.PositiveIntegerField(default=0)),
                ('saldo', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('sucursal', models.ForeignKey(default='ES', on_delete=django.db.models.deletion.CASCADE, to='inv.Sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='bodega_historico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('existencia', models.PositiveIntegerField(default=0)),
                ('saldo', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('bodega', models.ForeignKey(default='ESTR', on_delete=django.db.models.deletion.CASCADE, to='inv.Bodega')),
            ],
        ),
    ]
