# Generated by Django 2.2.5 on 2020-04-24 16:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0004_auto_20200424_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='bodega_item_costo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('existencia', models.PositiveIntegerField(default=0)),
                ('saldo', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('bodega', models.ForeignKey(default='ESTR', on_delete=django.db.models.deletion.CASCADE, to='inv.Bodega')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.N4Item')),
            ],
            options={
                'unique_together': {('bodega', 'item')},
            },
        ),
        migrations.CreateModel(
            name='bodega_item_costo_historico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('existencia', models.PositiveIntegerField(default=0)),
                ('saldo', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('bodega', models.ForeignKey(default='ESTR', on_delete=django.db.models.deletion.CASCADE, to='inv.Bodega')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.N4Item')),
            ],
            options={
                'unique_together': {('bodega', 'item', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='sucursal_item_costo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('existencia', models.PositiveIntegerField(default=0)),
                ('saldo', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.N4Item')),
                ('sucursal', models.ForeignKey(default='ES', on_delete=django.db.models.deletion.CASCADE, to='inv.Sucursal')),
            ],
            options={
                'unique_together': {('sucursal', 'item')},
            },
        ),
        migrations.CreateModel(
            name='sucursal_item_costo_historico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('existencia', models.PositiveIntegerField(default=0)),
                ('saldo', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.N4Item')),
                ('sucursal', models.ForeignKey(default='ES', on_delete=django.db.models.deletion.CASCADE, to='inv.Sucursal')),
            ],
            options={
                'unique_together': {('sucursal', 'item', 'fecha')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='sucursal_historico',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='sucursal_historico',
            name='sucursal',
        ),
        migrations.DeleteModel(
            name='bodega_historico',
        ),
        migrations.DeleteModel(
            name='sucursal_historico',
        ),
    ]
