# Generated by Django 2.2.5 on 2020-04-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0005_auto_20200424_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='n3producto',
            name='naturaleza',
            field=models.CharField(choices=[('C', 'Combo'), ('D', 'Descuento'), ('E', 'Elemento'), ('P', 'Procesado'), ('S', 'Servicio'), ('U', 'Unico')], default='U', max_length=1),
        ),
    ]
