# Generated by Django 2.2.5 on 2020-05-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0008_auto_20200513_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='n3producto',
            name='entero',
            field=models.CharField(choices=[('N', 'Se vende por partes de la medida'), ('S', 'Se vende por toda la medida')], default='S', max_length=1),
        ),
    ]
