# Generated by Django 2.2.5 on 2020-05-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0009_auto_20200516_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='n3producto',
            name='entero',
            field=models.CharField(choices=[('S', 'Se vende por toda la medida'), ('N', 'Se vende por partes de la medida')], default='S', max_length=1),
        ),
    ]
