# Generated by Django 2.2.5 on 2020-05-29 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0010_auto_20200516_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='n3producto',
            name='codfabrica',
        ),
        migrations.CreateModel(
            name='CodigoFabrica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codfabrica', models.CharField(max_length=255)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.N2Familia')),
            ],
            options={
                'unique_together': {('producto', 'codfabrica')},
            },
        ),
    ]
