# Generated by Django 2.2.5 on 2020-05-29 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0011_auto_20200529_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigofabrica',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.N3Producto'),
        ),
    ]
