# Generated by Django 2.2.5 on 2020-04-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado_prestamos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=40, unique=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('referencia', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=100)),
                ('debe', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('haber', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='Fondos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=20, unique=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Formas_recuperacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30, unique=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Frecuencias_pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30, unique=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Monedas',
            fields=[
                ('id_moneda', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=7, unique=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamos',
            fields=[
                ('referencia', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('consecutivo', models.BigIntegerField(unique=True)),
                ('fecha_otorgado', models.DateField(auto_now_add=True)),
                ('fecha_vence', models.DateField()),
                ('principal', models.FloatField(default=0)),
                ('tipo_cambio', models.FloatField(default=0)),
                ('principal_ofi', models.FloatField(default=0)),
                ('numcuotas', models.IntegerField(default=0)),
                ('cuota', models.FloatField(default=0)),
                ('intcorriente', models.FloatField(default=3)),
                ('intmoratorio', models.FloatField(default=1)),
                ('gracia', models.IntegerField(default=0)),
                ('notas', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50, unique=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto_tipos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Roc',
            fields=[
                ('numero', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tipo', models.CharField(default='RC', max_length=2)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('concepto', models.TextField(blank=True, default='Abono', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipos_garantias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50, unique=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
