# Generated by Django 2.2.5 on 2020-04-23 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inv', '0001_initial'),
        ('cartera', '0001_initial'),
        ('vta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roc',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vta.Cliente'),
        ),
        migrations.AddField(
            model_name='roc',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vta.Vendedores'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartera.Producto_tipos'),
        ),
        migrations.AddField(
            model_name='prestamos',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vta.Cliente'),
        ),
        migrations.AddField(
            model_name='prestamos',
            name='estado_prestamo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartera.Estado_prestamos'),
        ),
        migrations.AddField(
            model_name='prestamos',
            name='fondo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartera.Fondos'),
        ),
        migrations.AddField(
            model_name='prestamos',
            name='formas_recuperacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartera.Formas_recuperacion'),
        ),
        migrations.AddField(
            model_name='prestamos',
            name='frecuencia_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartera.Frecuencias_pago'),
        ),
        migrations.AddField(
            model_name='prestamos',
            name='moneda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartera.Monedas'),
        ),
        migrations.AddField(
            model_name='prestamos',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartera.Producto'),
        ),
        migrations.AddField(
            model_name='prestamos',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.Sucursal'),
        ),
        migrations.AddField(
            model_name='prestamos',
            name='tipo_garantia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartera.Tipos_garantias'),
        ),
        migrations.AddField(
            model_name='estadocuenta',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vta.Cliente'),
        ),
    ]
