# Generated by Django 2.2.5 on 2020-08-20 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='catEnunciado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='catInforme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='catPregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidencias.catEnunciado')),
            ],
        ),
        migrations.CreateModel(
            name='catRespuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidencias.catEnunciado')),
            ],
        ),
        migrations.CreateModel(
            name='catResultado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='supervisor',
            fields=[
                ('codigoempleado', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='documentoMsr',
            fields=[
                ('referencia', models.CharField(default='ES-31129999-001', max_length=15, primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('turno', models.CharField(choices=[('D', 'Diurno'), ('N', 'Nocturno')], default='D', max_length=1)),
                ('corte', models.CharField(max_length=4)),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidencias.catInforme')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidencias.supervisor')),
            ],
        ),
        migrations.CreateModel(
            name='documentoDet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TextField(null=True)),
                ('nota', models.TextField(null=True)),
                ('maestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidencias.documentoMsr')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidencias.catPregunta')),
                ('respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidencias.catRespuesta')),
            ],
        ),
        migrations.CreateModel(
            name='catSeccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidencias.catInforme')),
            ],
        ),
        migrations.AddField(
            model_name='catrespuesta',
            name='resultado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidencias.catResultado'),
        ),
        migrations.AddField(
            model_name='catpregunta',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidencias.catSeccion'),
        ),
        migrations.AddField(
            model_name='catenunciado',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidencias.catSeccion'),
        ),
    ]
