# Generated by Django 2.2.5 on 2020-08-20 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catenunciado',
            name='seccion',
        ),
        migrations.CreateModel(
            name='catArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidencias.catSeccion')),
            ],
        ),
        migrations.AddField(
            model_name='catenunciado',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='incidencias.catArea'),
            preserve_default=False,
        ),
    ]
