# Generated by Django 2.2.5 on 2020-08-20 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0002_auto_20200820_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catpregunta',
            name='seccion',
        ),
        migrations.AddField(
            model_name='catpregunta',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='incidencias.catArea'),
            preserve_default=False,
        ),
    ]
