# Generated by Django 2.2.5 on 2020-08-20 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0003_auto_20200820_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catenunciado',
            name='area',
        ),
    ]
