# Generated by Django 2.2.5 on 2020-08-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0004_remove_catenunciado_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentomsr',
            name='corte',
            field=models.CharField(max_length=20),
        ),
    ]
