# Generated by Django 2.2.5 on 2020-04-23 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cajas',
            fields=[
                ('codigo', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('no_caja', models.IntegerField(unique=True)),
                ('monto_max', models.FloatField(default=10000)),
                ('suc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.Sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='Naturaleza',
            fields=[
                ('codigo', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCambio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('oficial', models.FloatField()),
                ('compra', models.FloatField()),
                ('venta', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoMovimiento',
            fields=[
                ('codigo', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('movimiento', models.CharField(max_length=50)),
                ('naturaleza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caja.Naturaleza')),
            ],
        ),
        migrations.CreateModel(
            name='Registros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('referencia', models.CharField(max_length=50)),
                ('total', models.FloatField(default=0)),
                ('real', models.FloatField(default=0)),
                ('nio_in', models.FloatField(default=0)),
                ('usd_in', models.FloatField(default=0)),
                ('tarjeta', models.FloatField(default=0)),
                ('fenibillete', models.FloatField(default=0)),
                ('nio_out', models.FloatField(default=0)),
                ('usd_out', models.FloatField(default=0)),
                ('voucher', models.CharField(blank=True, max_length=20, null=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caja.Cajas')),
                ('estado', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='inv.Estado')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caja.TipoMovimiento')),
            ],
        ),
    ]
