# Generated by Django 2.1.7 on 2020-06-02 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inv', '0001_initial'),
        ('caja', '0001_initial'),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('identificacion', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('correo', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_civil', models.CharField(choices=[('C', 'Casado / Casada'), ('U', 'Unión'), ('S', 'Soltero / Soltera'), ('V', 'Viudo / Viuda')], default='S', max_length=1)),
                ('dependientes', models.IntegerField(default=0)),
                ('limite_credito', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('tipo', models.CharField(default='N', max_length=1)),
                ('magnetico', models.CharField(max_length=255, unique=True)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='ClienteDireccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=255)),
                ('valido', models.BooleanField(default=True)),
                ('predeterminado', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vta.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ClienteDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('nota', models.CharField(blank=True, max_length=100, null=True)),
                ('rutaimagen', models.CharField(max_length=500)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vta.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ClienteTelefono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=15)),
                ('operador', models.CharField(choices=[('C', 'Claro'), ('M', 'Movistar'), ('O', 'Cootel')], default='C', max_length=1)),
                ('valido', models.BooleanField(default=True)),
                ('predeterminado', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vta.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ClienteVehiculo',
            fields=[
                ('chasis', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('placa', models.CharField(blank=True, max_length=10, null=True)),
                ('motor', models.CharField(max_length=50)),
                ('circulacion', models.CharField(blank=True, max_length=9, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=100, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vta.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ClienteVehiculoColor',
            fields=[
                ('codigo', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Condicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('Contado', 'Contado'), ('Credito', 'Credito')], max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cooperativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('segmento', models.CharField(choices=[('0', 'Particular'), ('1', 'Cooperativa'), ('2', 'Empleados')], default='1', max_length=1)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ExoRubroCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('referencia', models.CharField(default='nothing', max_length=50)),
                ('cooperativa', models.CharField(default='nothing', max_length=100)),
                ('costo', models.FloatField(default=0)),
                ('precio', models.FloatField(default=0)),
                ('unidades', models.FloatField(default=0)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vta.Cliente')),
                ('rubro', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inv.ExoRubro')),
            ],
        ),
        migrations.CreateModel(
            name='Facturadet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidades', models.IntegerField()),
                ('preciofinal', models.DecimalField(decimal_places=4, max_digits=19)),
                ('descuento', models.DecimalField(decimal_places=4, max_digits=19)),
                ('impuesto', models.DecimalField(decimal_places=4, max_digits=19)),
                ('costo', models.DecimalField(decimal_places=4, max_digits=19)),
                ('comercializacion', models.SmallIntegerField(default=0)),
                ('devuelto', models.IntegerField(default=0)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.Bodega')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.N4Item')),
            ],
        ),
        migrations.CreateModel(
            name='Facturamsr',
            fields=[
                ('referencia', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('serie', models.CharField(max_length=20, unique=True)),
                ('fechaemision', models.DateTimeField(auto_now_add=True)),
                ('fechavencimiento', models.DateField()),
                ('membresia', models.IntegerField(default=1)),
                ('cooperativa', models.IntegerField(default=1)),
                ('preciofinaltotal', models.DecimalField(decimal_places=4, max_digits=19)),
                ('descuentotal', models.DecimalField(decimal_places=4, max_digits=19)),
                ('extradescuento', models.FloatField(default=0)),
                ('impuestototal', models.DecimalField(decimal_places=4, max_digits=19)),
                ('impreso', models.SmallIntegerField(default=0)),
                ('nombre', models.CharField(blank=True, max_length=80, null=True)),
                ('cct', models.CharField(blank=True, default='0', max_length=20, null=True)),
                ('monto_cct', models.FloatField(default=0)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vta.Cliente')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Forma_pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, unique=True)),
                ('condicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vta.Condicion')),
            ],
        ),
        migrations.CreateModel(
            name='IncentivoDet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('debe', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.N4Item')),
            ],
        ),
        migrations.CreateModel(
            name='IncentivoMsr',
            fields=[
                ('referencia', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ajuste', models.CharField(choices=[('Entrada', 'Entrada'), ('Salida', 'Salida')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('centro_costo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.CentroCosto')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vta.Cliente')),
                ('estado', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='inv.Estado')),
            ],
        ),
        migrations.CreateModel(
            name='InstanciaFactMsr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaemision', models.DateTimeField(auto_now_add=True)),
                ('fechavencimiento', models.DateField()),
                ('membresia', models.IntegerField(default=1)),
                ('cooperativa', models.IntegerField(default=1)),
                ('preciofinaltotal', models.DecimalField(decimal_places=4, max_digits=19)),
                ('descuentotal', models.DecimalField(decimal_places=4, max_digits=19)),
                ('extradescuento', models.FloatField(default=0)),
                ('impuestototal', models.DecimalField(decimal_places=4, max_digits=19)),
                ('nombre', models.CharField(blank=True, max_length=80, null=True)),
                ('cct', models.CharField(blank=True, default='0', max_length=20, null=True)),
                ('monto_cct', models.FloatField(default=0)),
                ('origen', models.CharField(default='Fact', max_length=20)),
                ('borrador', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inv.TempCatalogoMsr')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vta.Cliente')),
                ('formapago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vta.Forma_pago')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.Sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30, unique=True)),
                ('prioridad', models.IntegerField(default=0)),
                ('descuento', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='PermisosCliente',
            fields=[
                ('modelo', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Proformadet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidades', models.IntegerField()),
                ('preciobase', models.FloatField()),
                ('descuento', models.FloatField()),
                ('impuesto', models.FloatField()),
                ('bodega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inv.Bodega')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.N4Item')),
            ],
        ),
        migrations.CreateModel(
            name='Proformamsr',
            fields=[
                ('referencia', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fechaemision', models.DateTimeField(auto_now_add=True)),
                ('fechavencimiento', models.DateField()),
                ('membresia', models.IntegerField(default=1)),
                ('cooperativa', models.IntegerField(default=1)),
                ('descuento', models.FloatField()),
                ('extradescuento', models.FloatField(default=0)),
                ('impuesto', models.FloatField()),
                ('costo', models.FloatField()),
                ('nombre', models.CharField(blank=True, max_length=80, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vta.Cliente')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.Estado')),
                ('formapago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vta.Forma_pago')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.Sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='TempCombo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.TempCatalogo')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.N4Item')),
            ],
        ),
        migrations.CreateModel(
            name='Uniones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Vendedores',
            fields=[
                ('identificacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('codigo_empleado', models.CharField(max_length=5, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('cajero', models.ForeignKey(default='ES01', on_delete=django.db.models.deletion.CASCADE, to='caja.Cajas')),
            ],
        ),
        migrations.AddField(
            model_name='proformamsr',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vta.Vendedores'),
        ),
        migrations.AddField(
            model_name='proformadet',
            name='referencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vta.Proformamsr'),
        ),
        migrations.AddField(
            model_name='instanciafactmsr',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vta.Vendedores'),
        ),
        migrations.AddField(
            model_name='incentivodet',
            name='referencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vta.IncentivoMsr'),
        ),
        migrations.AddField(
            model_name='facturamsr',
            name='formapago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vta.Forma_pago'),
        ),
        migrations.AddField(
            model_name='facturamsr',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.Sucursal'),
        ),
        migrations.AddField(
            model_name='facturamsr',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vta.Vendedores'),
        ),
        migrations.AddField(
            model_name='facturadet',
            name='referencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vta.Facturamsr'),
        ),
        migrations.AddField(
            model_name='facturadet',
            name='tipoexo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.ExoTipo'),
        ),
        migrations.AddField(
            model_name='cooperativa',
            name='union',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vta.Uniones'),
        ),
        migrations.AddField(
            model_name='clientevehiculo',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vta.ClienteVehiculoColor'),
        ),
        migrations.AddField(
            model_name='clientevehiculo',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.ModeloVehiculo'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cooperativa',
            field=models.ManyToManyField(default=1, to='vta.Cooperativa'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='membresia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vta.Membresia'),
        ),
    ]
