# Generated by Django 2.2.5 on 2020-04-23 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CotizacionDet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidades', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CotizacionMsr',
            fields=[
                ('referencia', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('notas', models.CharField(blank=True, default='.', max_length=255, null=True)),
                ('finalizado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EntradaMercaderiaDet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidades', models.FloatField()),
                ('costo', models.FloatField()),
                ('impuesto', models.FloatField()),
                ('fecha_venc', models.CharField(default='2020-04-16', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='EntradaMercaderiaMsr',
            fields=[
                ('referencia', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('facturas', models.CharField(max_length=255)),
                ('fecha_vencimiento', models.DateTimeField()),
                ('poliza', models.CharField(default='0', max_length=50)),
                ('costo_compra', models.FloatField(default=0)),
                ('costo_iva', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenCompraDet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidades', models.FloatField()),
                ('despachado', models.FloatField(default=0)),
                ('costo', models.FloatField()),
                ('impuesto', models.FloatField(default=0)),
                ('fecha_venc', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenCompraMsr',
            fields=[
                ('referencia', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('vencimiento', models.DateField(null=True)),
                ('importado', models.BooleanField(default=False)),
                ('recibido', models.BooleanField(default=False)),
                ('tipo', models.CharField(choices=[('L', 'Local'), ('I', 'Internacional')], default='L', max_length=1)),
                ('moneda', models.CharField(choices=[('C', 'Cordobas'), ('D', 'Dolares')], default='C', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('abreviatura', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('ruc', models.CharField(max_length=20, unique=True)),
                ('web', models.CharField(blank=True, default='No posee', max_length=45, null=True)),
                ('comentario', models.CharField(blank=True, default='.', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TempRem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidades', models.FloatField(default=0)),
                ('costo', models.FloatField(default=0)),
                ('impuesto', models.FloatField(default=0.15)),
                ('editable', models.BooleanField(default=True)),
                ('fecha_venc', models.CharField(blank=True, max_length=10, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.N4Item')),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='com.OrdenCompraMsr')),
                ('tipo_exo', models.ForeignKey(default='G', on_delete=django.db.models.deletion.CASCADE, to='inv.ExoTipo')),
            ],
        ),
        migrations.CreateModel(
            name='ProveedorDireccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(default='505', max_length=255)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='com.Proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='ProveedorContacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefonos', models.CharField(default='505', max_length=255)),
                ('cargo', models.CharField(max_length=100)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='com.Proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='ProformaMsr',
            fields=[
                ('referencia', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('notas', models.CharField(default='.', max_length=255)),
                ('finalizado', models.BooleanField(default=False)),
                ('importado', models.BooleanField(default=False)),
                ('cotizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='com.CotizacionMsr')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='com.Proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='ProforDet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidades', models.FloatField()),
                ('costo', models.FloatField()),
                ('impuesto', models.FloatField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.N4Item')),
                ('referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='com.ProformaMsr')),
            ],
        ),
    ]
