# Generated by Django 2.2.5 on 2020-04-23 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('com', '0001_initial'),
        ('inv', '0001_initial'),
        ('vta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompramsr',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vta.Cliente'),
        ),
        migrations.AddField(
            model_name='ordencompramsr',
            name='condicion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vta.Condicion'),
        ),
        migrations.AddField(
            model_name='ordencompramsr',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.Estado'),
        ),
        migrations.AddField(
            model_name='ordencompramsr',
            name='proforma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='com.ProformaMsr'),
        ),
        migrations.AddField(
            model_name='ordencompramsr',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='com.Proveedor'),
        ),
        migrations.AddField(
            model_name='ordencompradet',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.N4Item'),
        ),
        migrations.AddField(
            model_name='ordencompradet',
            name='referencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='com.OrdenCompraMsr'),
        ),
        migrations.AddField(
            model_name='entradamercaderiamsr',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vta.Cliente'),
        ),
        migrations.AddField(
            model_name='entradamercaderiamsr',
            name='condicion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vta.Condicion'),
        ),
        migrations.AddField(
            model_name='entradamercaderiamsr',
            name='estado',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='inv.Estado'),
        ),
        migrations.AddField(
            model_name='entradamercaderiamsr',
            name='ordenes_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='com.OrdenCompraMsr'),
        ),
        migrations.AddField(
            model_name='entradamercaderiamsr',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='com.Proveedor'),
        ),
        migrations.AddField(
            model_name='entradamercaderiadet',
            name='bodega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.Bodega'),
        ),
        migrations.AddField(
            model_name='entradamercaderiadet',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.N4Item'),
        ),
        migrations.AddField(
            model_name='entradamercaderiadet',
            name='referencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='com.EntradaMercaderiaMsr'),
        ),
        migrations.AddField(
            model_name='entradamercaderiadet',
            name='tipo_exo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.ExoTipo'),
        ),
        migrations.AddField(
            model_name='cotizacionmsr',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='com.Proveedor'),
        ),
        migrations.AddField(
            model_name='cotizaciondet',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.N4Item'),
        ),
        migrations.AddField(
            model_name='cotizaciondet',
            name='referencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='com.CotizacionMsr'),
        ),
        migrations.AlterUniqueTogether(
            name='profordet',
            unique_together={('referencia', 'item')},
        ),
        migrations.AlterUniqueTogether(
            name='ordencompradet',
            unique_together={('referencia', 'item')},
        ),
        migrations.AlterUniqueTogether(
            name='entradamercaderiadet',
            unique_together={('referencia', 'item', 'bodega')},
        ),
        migrations.AlterUniqueTogether(
            name='cotizaciondet',
            unique_together={('referencia', 'item')},
        ),
    ]
