# Generated by Django 2.2.5 on 2020-04-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com', '0002_auto_20200423_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradamercaderiadet',
            name='unidades',
            field=models.IntegerField(default=0),
        ),
    ]
