# Generated by Django 2.2.5 on 2020-04-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com', '0003_auto_20200427_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradamercaderiadet',
            name='devuelto',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='entradamercaderiadet',
            name='unidades',
            field=models.FloatField(),
        ),
    ]
